### ISSUE TITLE
Lockscreen Wallpaper Not Changing

### ISSUE THREAD

**Issue by puppyshark7** [t1m0thyj/WinDynamicDesktop#549] opened 2023-11-27 23:25 UTC
- WDD Version: 5.3.1
- OS Version: Windows 11 23H2

Steps to Reproduce:

1. Set a wallpaper in WDD.
2. Right click on the tray and toggle Change Lockscreen Image to on
3. Lock the computer

My lockscreen is still stuck on the default wallpaper provided by Microsoft. My desktop wallpaper changes. In the personalization, the image (macOS Sonoma) shows up in the desktop wallpaper but not the lockscreen. Any ideas how this can be fixed?

Are you using the Microsoft Store version of WDD?: Yes

**Comment by t1m0thyj** [comment] 2024-01-31 04:21
Duplicate of #548

**Closed by t1m0thyj** 2024-01-31 04:21 UTC
