### ISSUE TITLE
(System.ArgumentOutOfRangeException) The process was terminated due to an unhandled exception. at each start up

### ISSUE THREAD

**Issue by gonace** [t1m0thyj/WinDynamicDesktop#118] opened 2019-04-24 04:20 UTC
```
Application: WinDynamicDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.DateTime.Add(Double, Int32)
   at SunCalcNet.Utils.DateTimeUtils.FromJulian(Double)
   at SunCalcNet.SunCalc.GetSunPhases(System.DateTime, Double, Double)
   at WinDynamicDesktop.SunriseSunsetService.GetSunPhases(System.DateTime, System.String, System.String)
   at WinDynamicDesktop.SunriseSunsetService.GetSolarData(System.DateTime)
   at WinDynamicDesktop.WallpaperChangeScheduler.RunScheduler(Boolean)
   at WinDynamicDesktop.AppContext..ctor(System.String[])
   at WinDynamicDesktop.Program.Main(System.String[])
```

```
Faulting application name: WinDynamicDesktop.exe, version: 3.1.0.0, time stamp: 0x5c7e8300
Faulting module name: KERNELBASE.dll, version: 10.0.17763.404, time stamp: 0x3424aead
Exception code: 0xe0434352
Fault offset: 0x0011c6f2
Faulting process id: 0x22f8
Faulting application start time: 0x01d4fa5330069e13
Faulting application path: C:\Program Files\WindowsApps\38719TimothyJohnson.WinDynamicDesktop_3.1.0.0_neutral__rfarkse4rn21a\WinDynamicDesktop\WinDynamicDesktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: f9d64b33-c7a2-40fe-91cd-9f0190e79b7d
Faulting package full name: 38719TimothyJohnson.WinDynamicDesktop_3.1.0.0_neutral__rfarkse4rn21a
Faulting package-relative application ID: App
```

When reporting a bug please provide:
 - Installed it, rebooted and problem appears (have tried uninstalling and installing with the same result)
 - Windows 10
 - WinDynamicDesktop 3.1.0
 - Microsoft Store

**Comment by gonace** [comment] 2019-04-24 04:32
I've tried installing it from the executable provided there on GitHub and the same problem appears with that install.

**Comment by t1m0thyj** [comment] 2019-04-24 04:36
Do you live in a Scandinavian country or somewhere near the North Pole? If so the sunrise and sunset times sometimes fail to calculate because of polar day/night, I plan on fixing this in the next version of the app.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gonace** [comment] 2019-04-24 05:36
Hi
Actually, I do (Sweden), that sounds great, I'll keep an eye on new releases!

Thanks

**Comment by t1m0thyj** [comment] 2019-04-25 11:29
Closing this as duplicate of #104, will comment there when fixed. Nothing wrong with creating this issue since it wasn't obvious what was causing the problem.

**Closed by t1m0thyj** 2019-04-25 11:29 UTC
Labels: duplicate

**Comment by t1m0thyj** [comment] 2019-05-06 21:37
@gonace I'm implementing a fix for this, and was wondering which behavior you would prefer:

1. During times of the year when sun is up all day, wallpaper will cycle through daylight pictures all day long (or nighttime pictures during times when sun is down all day)
2. During times of the year when there is no sunrise or sunset, wallpaper will cycle based on artificial sunrise/sunset times like 6am and 6pm
