### ISSUE TITLE
Big Sur Theme always switches to black wallpaper, cannot be activated back.

### ISSUE THREAD

**Issue by jdrly** [t1m0thyj/WinDynamicDesktop#341] opened 2021-06-16 10:14 UTC
I did.

- WDD Version: 4.6.0
- OS Version:  W10 21H1

Steps to Reproduce:

1. Download Big Sure Theme
2. After a while it goes to black screen and cannot be reactived even after redownloading the theme itself.

Are you using the Microsoft Store version of WDD?: Yes

**Comment by t1m0thyj** [comment] 2021-07-06 04:25
This seems like it may be related to https://github.com/t1m0thyj/WinDynamicDesktop/issues/216:

> I can confirm now that the issue is only with the fourth image. The desktop goes dark even if I go to the picture itself (...WinDynamicDesktop\themes\Big_Sur\Big_Sur_5.jpg) right click on it and select "Set as desktop wallpaper". So is a Windows related bug? Somehow it is not able to set this image as a wallpaper.

What happens if you try this?

**Comment by jdrly** [comment] 2021-07-06 10:18
Yes, I can manually set every single one of them, excelt Big_Sur_5, then the themes changes to Simple Color Black instead of the wallpaper.

**Comment by jdrly** [comment] 2021-07-06 10:22
I have also tried resaving the picture via photoshop as jpg in lower quality, png but it ends up as a black screen aswell.

**Comment by t1m0thyj** [comment] 2021-07-09 02:55
Since the image is a valid JPEG that can be opened in programs like Photoshop, I don't think this is a WDD bug.
Please report this to Microsoft in the Feedback Hub app to increase publicity for the issue.

**Comment by yazan1107** [comment] 2021-12-01 10:45
i have the same exact problem when applying bigsur theme i get black screen!!

**Comment by yazan1107** [comment] 2021-12-03 08:09
the problem is with big_sur_5 wallpaper!! how can i fix this?

**Comment by t1m0thyj** [comment] 2022-07-12 04:13
Duplicate of #216 and a workaround is mentioned [here](https://github.com/t1m0thyj/WinDynamicDesktop/issues/216#issuecomment-657196199=)

**Closed by t1m0thyj** 2022-07-12 04:13 UTC
