### ISSUE TITLE
Failed to download images from Apple

### ISSUE THREAD

**Issue by zubi45** [t1m0thyj/WinDynamicDesktop#267] opened 2020-11-06 12:20 UTC
When click for downloading a new image i got an error message: Failed to download image for 'chosen Theme' Do you want to try again. But that won't work. So I can't import any new images directly from the app.

**Comment by t1m0thyj** [comment] 2020-11-06 12:25
Are you behind a proxy or do you live in a country that restricts Internet access? As a workaround you should be able to download DDW files for macOS themes from here and import them into WDD: https://github.com/t1m0thyj/WDD-mac-themes/releases

**Comment by zubi45** [comment] 2020-11-06 13:01
It was only a problem, when installing the app from the windows app store. Since I reinstalled it from GitHub, there was now problem any more.

**Comment by t1m0thyj** [comment] 2020-11-13 06:05
Can't reproduce the issue with downloading from Microsoft Store. Closing for now, feel free to reopen if more details can be provided.

**Closed by t1m0thyj** 2020-11-13 06:05 UTC
