### ISSUE TITLE
wallpaper do not refresh itself in other mutli-task desktop screen

### ISSUE THREAD

**Issue by jack8096** [t1m0thyj/WinDynamicDesktop#523] opened 2023-04-08 15:07 UTC
- WDD Version: 5.2.1
- OS Version: win 11

suppose you set up WDD wallpaper after that creating new multi-task desktop the WDD do not change wallpaper of newly created desktop at the time of change to the 

Steps to Reproduce:

1.changing multi-task desktop

Are you using the Microsoft Store version of WDD?: Yes

**Comment by t1m0thyj** [comment] 2023-04-20 04:16
Closing as duplicate of #475. Since WDD v5.1.0 the feature to sync virtual desktops is still available but must be installed separately as a script:
> Note: This version removes syncing wallpaper across virtual desktops in Windows 11 which used an experimental API that is too unstable to support. If you still want this functionality, install the [Sync Virtual Desktops](https://github.com/t1m0thyj/WDD-scripts/tree/master/experimental#synchronize-virtual-desktops) script.

**Closed by t1m0thyj** 2023-04-20 04:16 UTC
