### ISSUE TITLE
Manual Choose for Pictures.

### ISSUE THREAD

**Issue by BasilAlfattal** [t1m0thyj/WinDynamicDesktop#271] opened 2020-11-21 22:45 UTC
Hello , I was wonder if you could give the option to choose manually between wallpapers of the selected theme , and other option to resume auto changing of wallpapers . 
I Believe that will be great features to be add .   

Thanks : )

**Comment by t1m0thyj** [comment] 2020-12-02 05:11
This seems like duplicate of https://github.com/t1m0thyj/WinDynamicDesktop/issues/256. As mentioned in comment there, this is not a planned feature for WDD since you can create custom themes. Feel free to reopen if I've misunderstood the request.

**Closed by t1m0thyj** 2020-12-02 05:11 UTC
