### ISSUE TITLE
Error when applying theme to lock screen

### ISSUE THREAD

**Issue by InfinitGit** [t1m0thyj/WinDynamicDesktop#564] opened 2024-02-18 18:58 UTC
- WDD Version: 5.4.1 UWP
- OS Version: Win11 Home 23H2

Steps to Reproduce:

1. Change display selection to "Lock screen"
2. Attempt to apply any theme to the "Lock screen"

**Error:**
![image](https://github.com/t1m0thyj/WinDynamicDesktop/assets/124841095/67f03970-c049-4336-9f88-1a6d60f9bfa0)
 
**Logfile:**
 "[2024-02-18 18:52:13.988] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WinDynamicDesktop.EventScheduler.Run(Boolean forceImageUpdate, DisplayEvent overrideEvent)
   at WinDynamicDesktop.ThemeDialog.ApplySelectedTheme()
   at WinDynamicDesktop.ThemeDialog.applyButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)"

Are you using the Microsoft Store version of WDD?: Yes

**Comment by t1m0thyj** [comment] 2024-02-19 16:57
@InfinitGit Thanks for reporting this. So far I haven't been able to reproduce the issue - am able to apply themes to the lock screen on both a laptop and a multi-monitor desktop setup. How many monitors/displays do you have and which theme do you have selected for each one?

Also if you navigate to [the folder where WinDynamicDesktop EXE is located](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed), there should be a "report.log" file that contains a more detailed error report. Please upload this file to the issue.

**Comment by t1m0thyj** [comment] 2024-02-21 05:43
@Ghadeem The bug you've reported is different from the lock screen error - please see https://github.com/t1m0thyj/WinDynamicDesktop/issues/563#issuecomment-1955934762 for how to fix it. Thanks for attaching the logs, they helped me to diagnose the issue.

**Comment by t1m0thyj** [comment] 2024-02-21 05:44
@Ghadeem The bug you've reported is different from the lock screen error - please see https://github.com/t1m0thyj/WinDynamicDesktop/issues/563#issuecomment-1955934762 for how to fix it. Thanks for attaching the logs, they helped me to diagnose the issue.

@InfinitGit Please provide logs when you have a chance (see my comment above). I still haven't been able to reproduce the lock screen issue.

**Comment by t1m0thyj** [comment] 2024-02-21 13:03
@InfinitGit After further investigation I think I identified the cause of the error. Please download the latest test build from [here](https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/7989342859) and try to apply a theme to the lock screen again. If it still doesn't work, then please send logs as I mentioned in earlier comment.

**Comment by t1m0thyj** [comment] 2024-02-28 17:13
Fixed in 5.4.2

**Closed by t1m0thyj** 2024-02-28 17:13 UTC
Labels: bug, priority-medium, pending-release
