### ISSUE TITLE
I am trying to test a translation I am working on the poeditor site

### ISSUE THREAD

**Issue by masterjunior24** [t1m0thyj/WinDynamicDesktop#254] opened 2020-10-10 13:55 UTC
**Description**
I used this [guide](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Translating-the-app) to test an incomplete translation but the app would crash when I would try to restart. This is the log file
[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/5359129/WinDynamicDesktop.exe.log)

**Comment by t1m0thyj** [comment] 2020-10-10 14:15
@masterjunior24 What language are you trying to test? This config in "settings.conf" works fine for me:
![image](https://user-images.githubusercontent.com/22344007/95657255-7e6e2880-0ae1-11eb-8c14-27a91820ddac.png)

**Comment by masterjunior24** [comment] 2020-10-10 14:57
> @masterjunior24 What language are you trying to test? This config in "settings.conf" works fine for me:
> ![image](https://user-images.githubusercontent.com/22344007/95657255-7e6e2880-0ae1-11eb-8c14-27a91820ddac.png)

I am trying to test greek but the error occurs when I add an api token

**Comment by t1m0thyj** [comment] 2020-10-10 17:47
@masterjunior24 What language ID are you using for Greek? `el` works ok for me.

**Comment by masterjunior24** [comment] 2020-10-11 09:01
I put this in the config file and it still crashes
![image](https://user-images.githubusercontent.com/59114638/95674529-826d7980-0bb9-11eb-9b6f-8a0581159df2.png)

**Comment by t1m0thyj** [comment] 2020-12-02 05:35
@masterjunior24 Any chance that your machine uses an Internet proxy? If so, I've identified an issue where the proxy is ignored by WDD for downloading translation files.

**Comment by sugar-king** [comment] 2021-04-20 10:46
I am having the same problem. After configuration of the token and language I get an error and this log: [WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/6342615/WinDynamicDesktop.exe.log)
If I remove the ```"language:" "XX",``` line, it can start once (rewriting that line using "en") with same error on second launch.

However, it seems to me that the problem is actually in the POEditor API. Using curl to list all my projects returns an empty list. And I get a 403 when trying to export the project.

**Comment by t1m0thyj** [comment] 2021-05-31 17:03
@sugar-king Thanks for finding the problem, I wasn't aware that only project owners can access a project with their API key. This should be fixed in WinDynamicDesktop 4.5.0 which was just released, you no longer have to provide an API key (see [updated instructions](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Translating-the-app#testing-new-translations)).

**Closed by t1m0thyj** 2021-05-31 17:03 UTC
Labels: bug
