### ISSUE TITLE
Can multi screen wallpaper settings be supported in the future？

### ISSUE THREAD

**Issue by ioslide** [t1m0thyj/WinDynamicDesktop#222] opened 2020-07-08 08:43 UTC

**Comment by t1m0thyj** [comment] 2020-07-19 03:23
Duplicate of #117:
> As a dual monitor user I agree this would be nice. However the system API for setting wallpapers doesn't allow specifying which monitor to display them on. In order for this to work it would likely be necessary to have the program stitch images together across the monitors, which would be complex based on how many there are and if they have different resolutions. Because of the difficulty involved I don't plan to implement this feature.

**Closed by t1m0thyj** 2020-07-19 03:23 UTC
