### ISSUE TITLE
UWP version autoexit in Win10 1809

### ISSUE THREAD

**Issue by quinaeus** [t1m0thyj/WinDynamicDesktop#67] opened 2018-10-05 12:26 UTC
---------------------------
Errors occurred
---------------------------
The logfile 'C:\Program Files\WindowsApps\38719TimothyJohnson.WinDynamicDesktop_2.0.2.1000_neutral__rfarkse4rn21a\WinDynamicDesktop\WinDynamicDesktop.exe.log' could not be opened:
 System.FormatException: 未能从“M/d”确定年、月和日期的顺序。

   在 System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)

   在 Innovative.SolarCalculator.ExcelFormulae.ToExcelDateValue(DateTime value)

   在 Innovative.SolarCalculator.SolarTimes.get_JulianDay()

   在 Innovative.SolarCalculator.SolarTimes.get_JulianCentury()

   在 Innovative.SolarCalculator.SolarTimes.get_ObliquityCorrection()

   在 Innovative.SolarCalculator.SolarTimes.get_VarY()

   在 Innovative.SolarCalculator.SolarTimes.get_EquationOfTime()

   在 Innovative.SolarCalculator.SolarTimes.get_SolarNoon()

   在 Innovative.SolarCalculator.SolarTimes.get_Sunrise()

   在 WinDynamicDesktop.SunriseSunsetService.GetWeatherData(String lat, String lon, String dateStr)

   在 WinDynamicDesktop.WallpaperChangeScheduler.GetWeatherData(String dateStr)

   在 WinDynamicDesktop.WallpaperChangeScheduler.RunScheduler()

   在 WinDynamicDesktop.AppContext..ctor()

   在 WinDynamicDesktop.Program.Main()

---------------------------
确定   
---------------------------

Thanks

**Comment by t1m0thyj** [comment] 2018-10-23 11:31
I believe this error was caused by a bug in the SolarCalculator library used by WinDynamicDesktop. It should be fixed in version 2.1.0 which was just released.

**Closed by t1m0thyj** 2018-10-23 11:31 UTC

**Comment by quinaeus** [comment] 2018-10-24 08:29
Thanks for your fix, it works well now!
