### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'Global\WinDynamicDesktop' is denied.

### ISSUE THREAD

**Issue by x2435Bits** [t1m0thyj/WinDynamicDesktop#277] opened 2021-01-07 06:47 UTC
`[2021-01-07 06:42:36.612] System.UnauthorizedAccessException: Access to the path 'Global\WinDynamicDesktop' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew, MutexSecurity mutexSecurity)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew)
   at WinDynamicDesktop.AppContext.HandleMultiInstance()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)`
   
   I get this error no matter with installer (portable or full) i try. Happening since i added my Device to an Azure. Wonder if thats related.

**Comment by mrericmendez** [comment] 2021-02-07 13:53
I just repro'd the issue but in a different way. Tried to install WDD on a newly-created user account, then tried to install another instance on said account:

1. As User 1 (hypothetical name for the first account I used) install WinDynamicDesktop (the build from Windows store)
2. Run thru the app, setting a theme to be sure the app launched & is running
3. As a different user, we'll refer to as User 2, install WDD from the Windows store
4. Run thru the app, setting a theme to be sure the app launched & is running
5. Observe the IO error "can't access Global\WinDynamicDesktop"
[System.UnauthorizedAccessException;.Access.to.the.path.'GlobalWinDynamicDesktop'.is.denied.277.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/5939086/System.UnauthorizedAccessException.Access.to.the.path.GlobalWinDynamicDesktop.is.denied.277.txt)


 Seems to be working if you uninstall & run thru the latest WDD-portable build (4.4.0)
[https://github.com/t1m0thyj/WinDynamicDesktop/releases/tag/v4.4.0]
Steps to workaround for now:

1. Uninstall all installed instances of WinDynamicDesktop
2. Copy the *WinDynamicDesktop_Portable.exe* to each user account in a safe place (example: C:\users\user1\example *or* C:\users\user2\example)
3. Run the .exe & it should be working as normal 

Please report any issues here if these steps didn't work and I'll take a look into it. Thanks for helping me actually comment by opening this bug, bc it has been a pain in the ass & didn't know what was going on til I found this workaround. Hope it helps someone else!

**Comment by t1m0thyj** [comment] 2021-05-31 17:07
@mrericmendez Thanks for finding the cause of the issue, I realized I shouldn't be using the "Global" prefix on the mutex name, because that prevents multiple users from being able to run WDD simultaneously on the same machine. This should be fixed in WinDynamicDesktop 4.5.0.

**Closed by t1m0thyj** 2021-05-31 17:07 UTC
