### ISSUE TITLE
error message at random times!

### ISSUE THREAD

**Issue by yazan1107** [t1m0thyj/WinDynamicDesktop#416] opened 2022-02-20 10:59 UTC
done

- WDD Version: 4.7.0
- OS Version: lastest
<img width="596" alt="image" src="https://user-images.githubusercontent.com/78726445/154839221-84bf0cbe-e77a-49db-be5b-a122ff177c4b.png">

Steps to Reproduce:

1. nothing random time while the app is running i receive this message!
this theme is currently running
<img width="699" alt="image" src="https://user-images.githubusercontent.com/78726445/154839283-75a09280-e3e5-4f27-a2ee-2166cbaff0b5.png">

Are you using the Microsoft Store version of WDD?: No
[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/8103812/WinDynamicDesktop.exe.log)

**Comment by t1m0thyj** [comment] 2022-03-31 04:59
Please try the new version of WDD (v5) and let me know if the issue is fixed.

**Comment by HypedDomi** [comment] 2022-04-02 18:19
> Please try the new version of WDD (v5) and let me know if the issue is fixed.
Im having the same Issue since i updated to v5
![image](https://user-images.githubusercontent.com/50876016/161396180-26c74f57-2740-431d-9e7f-b7133b762613.png)

**Comment by yazan1107** [comment] 2022-04-02 19:36
> Please try the new version of WDD (v5) and let me know if the issue is fixed.
this is today after the last update!
![image](https://user-images.githubusercontent.com/78726445/161398524-601ad4b9-a809-40fd-a54e-2b26228f762c.png)

**Comment by t1m0thyj** [comment] 2022-04-03 03:46
Sorry, could you please try version 5.0.1? I think the error is fixed now.

**Comment by HypedDomi** [comment] 2022-04-03 16:08
Yeah this seems to fixed the issue

**Closed** 2022-04-04 11:22 UTC
