### ISSUE TITLE
Turn on the night mode regularly during lunch break? 

### ISSUE THREAD

**Issue by S-Kee** [t1m0thyj/WinDynamicDesktop#380] opened 2021-10-29 01:29 UTC
If it can turn on the night mode regularly during lunch break?

**Comment by t1m0thyj** [comment] 2021-11-20 07:51
Closing as duplicate of #367. I don't plan to add an option in the app for this, but if night mode could be disable/enabled via CLI then you could automate this with a script.

**Closed by t1m0thyj** 2021-11-20 07:51 UTC
