### ISSUE TITLE
The logfile 'WinDynamicDesktop.exe.log' could not be opened

### ISSUE THREAD

**Issue by ptrkhh** [t1m0thyj/WinDynamicDesktop#86] opened 2019-01-02 19:46 UTC
I got this error on every startup:

```
---------------------------
Errors occurred
---------------------------
The logfile 'C:\Program Files\WindowsApps\38719TimothyJohnson.WinDynamicDesktop_2.3.0.0_neutral__rfarkse4rn21a\WinDynamicDesktop\WinDynamicDesktop.exe.log' could not be opened:
 Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'WinDynamicDesktop.ThemeConfig' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.

To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.

Path '', line 1, position 1.

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)

   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)

   at WinDynamicDesktop.JsonConfig.LoadTheme(String name)

   at WinDynamicDesktop.ThemeManager.Initialize()

   at WinDynamicDesktop.AppContext..ctor()

   at WinDynamicDesktop.Program.Main()

---------------------------
OK   
---------------------------

```

> Steps to reproduce it

I am not sure, but I recently installed some themes

> Log file (if it exists, see [here](/wiki/Finding-where-app-is-installed) for how to find it)

Log file specified there is located in C:\Program Files\WindowsApps, which is inaccessible by the user.

> Windows version (e.g. 7, 10)

Windows 10, October 2018 update

> WinDynamicDesktop version (e.g. 2.0.0)

2.3.0.0

> Installation source (e.g. installer, Microsoft Store, portable EXE)

Microsoft Store

**Comment by t1m0thyj** [comment] 2019-01-03 05:40
I'm not sure why WinDynamicDesktop is attempting to write the log file to that folder, it should be going into your Local AppData folder instead. You said that you recently installed some themes, could you give more details about this please? How long did the app work fine for before you installed themes? Were the themes you installed ones that you downloaded from GitHub or were they ones that you created?

One more thing, could you try resetting WinDynamicDesktop in the Windows 10 settings to start it from fresh and see if the problem reoccurs?

**Comment by tomtoxx** [comment] 2019-01-05 04:34
Same probleme here.
I have a fresh installation from the store without new themes.
I only thing I changed is "changeLockScreen":false to true in C:\Users\USER\AppData\Local\Packages\38719TimothyJohnson.WinDynamicDesktop_rfarkse4rn21a\LocalState\settings.conf

**Comment by t1m0thyj** [comment] 2019-01-05 05:45
@tomtoxx Both of these are bugs (changeLockScreen causing the app to crash and log file could not be opened). They will be fixed in the next version of the app which will hopefully be released next week.

**Comment by t1m0thyj** [comment] 2019-01-16 04:21
Both issues should be fixed in version 3.0 which was just released

**Comment by ptrkhh** [comment] 2019-01-21 15:49
Now I got this message, after updating to version 3.0

> ---------------------------
> Errors occurred
> ---------------------------
> See the logfile 'C:\Users\p\AppData\Local\Packages\38719TimothyJohnson.WinDynamicDesktop_rfarkse4rn21a\LocalState\WinDynamicDesktop.exe.log' for details
> ---------------------------
> OK   
> ---------------------------
>

**Comment by t1m0thyj** [comment] 2019-01-21 15:50
@ptrkhh Please attach the contents of the log file so I can see what the error is

**Comment by ptrkhh** [comment] 2019-01-21 18:16
```
System.ArgumentNullException: Value cannot be null.
Parameter name: collection
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at WinDynamicDesktop.ThemeManager.FindMissingThemes()
   at WinDynamicDesktop.ThemeManager.Initialize()
   at WinDynamicDesktop.AppContext..ctor()
   at WinDynamicDesktop.Program.Main()
System.ArgumentNullException: Value cannot be null.
Parameter name: collection
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at WinDynamicDesktop.ThemeManager.FindMissingThemes()
   at WinDynamicDesktop.ThemeManager.Initialize()
   at WinDynamicDesktop.AppContext..ctor()
   at WinDynamicDesktop.Program.Main()

```

**Comment by t1m0thyj** [comment] 2019-01-22 04:07
@ptrkhh Do you have any custom themes installed, or ones that you downloaded apart from the two bundled with the app? Based on the error message it seems like the problem is a theme that was made for an old version of the app. Theme JSON files are now required to include sections for "sunriseImageList" and "sunsetImageList", if this is missing in one of your theme files it could cause this error. If this is the case, it's still a bug in the app because even if the old theme files aren't compatible the error message should be more informative.

**Comment by ptrkhh** [comment] 2019-01-30 17:59
Only the one from your website (not from 24 Hours website). Its very likely though, as a carry-over from the old version before the update.

**Comment by t1m0thyj** [comment] 2019-03-27 16:44
Closing this since the last error reported is different from the original one. I believe it was due to an outdated theme being installed and downloading the latest ones from GitHub should work. If you continue to experience problems, feel free to create a new issue.

**Closed by t1m0thyj** 2019-03-27 16:44 UTC
