### ISSUE TITLE
Doesn't understand any city

### ISSUE THREAD

**Issue by Socialgiogi** [t1m0thyj/WinDynamicDesktop#22] opened 2018-06-20 03:14 UTC
I tried with a bunch of cities but it's not working, this is the report it return.

System.ArgumentOutOfRangeException: Argomento specificato non compreso nell'intervallo.
Nome parametro: The value for Latitude must be between -90° and 90°.
   in Innovative.SolarCalculator.SolarTimes.set_Latitude(Angle value)
   in Innovative.SolarCalculator.SolarTimes..ctor(DateTimeOffset forDate, Angle latitude, Angle longitude)
   in WinDynamicDesktop.SunriseSunsetService.GetWeatherData(String lat, String lon, String dateStr)
   in WinDynamicDesktop.WallpaperChangeScheduler.GetWeatherData(String dateStr)
   in WinDynamicDesktop.WallpaperChangeScheduler.StartScheduler(Boolean forceRefresh)
   in WinDynamicDesktop.InputDialog.okButton_Click(Object sender, EventArgs e)
   in System.Windows.Forms.Control.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnClick(EventArgs e)
   in System.Windows.Forms.Button.PerformClick()
   in System.Windows.Forms.Form.ProcessDialogKey(Keys keyData)
   in System.Windows.Forms.TextBoxBase.ProcessDialogKey(Keys keyData)
   in System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   in System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   in System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3110.0 built by: NET472REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WinDynamicDesktop
    Versione assembly: 1.2.0.0
    Versione Win32: 1.2.0.0
    Base di codice: file:///C:/Users/jonny/AppData/Local/Programs/WinDynamicDesktop/WinDynamicDesktop.exe
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0 built by: NET472REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0 built by: NET472REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0 built by: NET472REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    Versione assembly: 11.0.0.0
    Versione Win32: 1.2.0.0
    Base di codice: file:///C:/Users/jonny/AppData/Local/Programs/WinDynamicDesktop/WinDynamicDesktop.exe
----------------------------------------
System.Core
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3110.0 built by: NET472REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0 built by: NET472REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0 built by: NET472REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0 built by: NET472REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0 built by: NET472REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0 built by: NET472REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.IO.Compression.FileSystem
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
System.IO.Compression
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0 built by: NET472REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
mscorlib.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0 built by: NET472REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
RestSharp
    Versione assembly: 106.3.1.0
    Versione Win32: 1.2.0.0
    Base di codice: file:///C:/Users/jonny/AppData/Local/Programs/WinDynamicDesktop/WinDynamicDesktop.exe
----------------------------------------
System.Web
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0 built by: NET472REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Innovative.SolarCalculator
    Versione assembly: 2.0.2.0
    Versione Win32: 1.2.0.0
    Base di codice: file:///C:/Users/jonny/AppData/Local/Programs/WinDynamicDesktop/WinDynamicDesktop.exe
----------------------------------------
System.Runtime
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
Innovative.Geometry.Angle
    Versione assembly: 2.0.0.0
    Versione Win32: 1.2.0.0
    Base di codice: file:///C:/Users/jonny/AppData/Local/Programs/WinDynamicDesktop/WinDynamicDesktop.exe
----------------------------------------
System.Windows.Forms.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.3056.0 built by: NET472REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Debug JIT **************
Per abilitare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
abilitato.

Ad esempio:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

**Comment by t1m0thyj** [comment] 2018-06-20 03:43
Could you please provide examples of some of the cities you were trying? I can't reproduce this, it seems to be a problem for only a certain geographical area.

**Comment by Socialgiogi** [comment] 2018-06-20 04:06
I tried with London; Rome; Tokyo; Paris; Chicago; but none of these cities work...

**Comment by Sakal77** [comment] 2018-06-20 05:08
Hello. I had the same issue with different cities also and now app did not start with error message.
In log there is:
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at WinDynamicDesktop.SunriseSunsetService.GetWeatherData(String lat, String lon, String dateStr)
   at WinDynamicDesktop.WallpaperChangeScheduler.GetWeatherData(String dateStr)
   at WinDynamicDesktop.WallpaperChangeScheduler.StartScheduler(Boolean forceRefresh)
   at WinDynamicDesktop.FormWrapper..ctor()
   at WinDynamicDesktop.Program.Main()

and in conf I have:
{"location":"London","latitude":"52.5073219","longitude":"-0.1276474"}

Thank you for your time.

**Comment by timg83** [comment] 2018-06-20 06:17
Same issue here with latest release. Didn't had it with the previous release.

![afbeelding](https://user-images.githubusercontent.com/2979347/41640494-642803e6-7462-11e8-8fc3-a0bc49c009b7.png)

**Comment by MYRLOYY** [comment] 2018-06-20 08:50
same problem, I tried to enter the coordinates, cities and countries

**Comment by t1m0thyj** [comment] 2018-06-20 10:51
I am not able to reproduce this problem with any of the cities mentioned. Based on the information that has been reported, I believe the problem is with the `Double.Parse` function being used with the latitudes and longitudes. If your locale handles minus signs or decimal points differently than the US one, I suspect this is what is causing the problem. I'll try to release a potential fix for this tonight after work.

**Comment by LasseSLambertsen** [comment] 2018-06-20 12:39
@t1m0thyj 
Changing the decimal point to a comma, seems to get it to work.

**Comment by Shimmi** [comment] 2018-06-20 12:41
Hi @t1m0thyj,
I think I've been able to track down the issue. The issue will be related to Windows Localization. The US uses a dot for a decimal point whereas we, in Europe, use a comma. Seems the app/Windows/.net is quite localization sensitive :)

**Comment by pau1phi11ips** [comment] 2018-06-20 20:22
I tried "London, UK" and that worked fine for me.

**Comment by t1m0thyj** [comment] 2018-06-21 02:40
This should be fixed in version 1.2.1 which I just released.

**Closed by t1m0thyj** 2018-06-21 02:40 UTC

**Comment by Sakal77** [comment] 2018-06-21 10:45
1.2.1 works for me too. Thank you.

**Comment by Socialgiogi** [comment] 2018-06-21 11:13
1.2.1  works! smooth as butter!

thanks you
