### ISSUE TITLE
Can't seem to download ANY themes? 

### ISSUE THREAD

**Issue by Skrell** [t1m0thyj/WinDynamicDesktop#272] opened 2020-11-30 14:49 UTC
- WDD Version: 4.4 portable
- OS Version: Win 10

Steps to Reproduce:

1.  Launch Tool
2.  Download any theme

Are you using the Microsoft Store version of WDD?: No

Error log: 
[2020-11-30 14:33:08.344] System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
File name: 'System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at WinDynamicDesktop.ThemeLoader.ExtractTheme(String zipPath, String themeId)
   at WinDynamicDesktop.DownloadDialog.<>c__DisplayClass13_0.<OnDownloadFileCompleted>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WinDynamicDesktop.DownloadDialog.<OnDownloadFileCompleted>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by Skrell** [comment] 2020-11-30 15:10
Where is the temporary zip file being downloaded to for extraction?

**Comment by t1m0thyj** [comment] 2020-12-01 03:27
The temporary zip file is downloaded into the WDD "themes" folder.

Based on the attached error log, the problem isn't that WDD can't find the ZIP file, but that it can't find the `System.IO.Compression` DLL in your .NET Framework installation.

**Comment by manuelhzr** [comment] 2020-12-09 22:24
I have the same problem, I tried the Microsoft Store version and the installer, and both gave the error

**Comment by t1m0thyj** [comment] 2022-03-31 05:00
This error should be resolved in WDD v5, which no longer looks for .NET DLLs like `System.IO.Compression` on your system since .NET 6 is now bundled in the app.

**Closed by t1m0thyj** 2022-03-31 05:00 UTC
