### ISSUE TITLE
Windows not respecting theme change

### ISSUE THREAD

**Issue by bobshinkman** [t1m0thyj/WinDynamicDesktop#463] opened 2022-07-11 03:38 UTC
- WDD Version: 5.0.3
- OS Version: 22621.290

Steps to Reproduce:

1. Install [scripts](https://github.com/t1m0thyj/WDD-scripts/tree/master/stable) to change the Windows app and system themes with sunset/sunrise
2. Enable PowerShell scripts in the WDD app
3. Wait for time change or edit system clock to produce it
4. Open the start menu (this is often necessary to produce the system theme change after the app theme has already switched).

Are you using the Microsoft Store version of WDD?: No

Whenever a time change occurs, the Windows theme changes slightly but not fully. Examples here:
![2022-07-10 (1) (Large)](https://user-images.githubusercontent.com/66751461/178183993-d9c6d05b-2710-47a8-9402-569e7739ab96.png)
![2022-07-10 (Large)](https://user-images.githubusercontent.com/66751461/178184001-b3c218eb-1fac-40e1-82d0-ee9a0abd26ef.png)

Background color has changed but the UI text and some app icons haven't. It only fully switches over once I change it manually in the Windows system settings (usually by switching transparency effects off and on). 
![2022-07-10 (2) (Large)](https://user-images.githubusercontent.com/66751461/178184350-f9964bde-73a4-457f-ab54-a428c2516cf2.png)

**Comment by direrFlood** [comment] 2022-09-30 06:51
I am having the same issue.

**Comment by trintin94** [comment] 2022-10-12 19:09
I'm also having this issue

**Comment by t1m0thyj** [comment] 2023-01-03 01:41
Closing as duplicate of #427

**Closed by t1m0thyj** 2023-01-03 01:41 UTC
