### ISSUE TITLE
Problem setting WinDynamicDesktop theme in lock screen

### ISSUE THREAD

**Issue by guille003** [t1m0thyj/WinDynamicDesktop#289] opened 2021-03-03 15:28 UTC
Hello, I really love WinDynamicDesktop and I've been looking at it's themes. But I was wondering if there is a way to set my lock screen background image to be the same as the one being displayed in the background screen so that they change at the same time and they both use the chosen theme. Does WinDynamicDesktop allow that in some way? Please tell me how to do it, thank you so much.

**Comment by stiffbruno** [comment] 2021-03-08 17:52
I'd love to see that feature too.

**Comment by stiffbruno** [comment] 2021-03-08 17:58
I'd love to see that feature too. There is an open request already though: #257

**Comment by t1m0thyj** [comment] 2021-05-07 04:14
Duplicate of #257

**Closed by t1m0thyj** 2021-05-07 04:14 UTC
