### ISSUE TITLE
Application bar bug

### ISSUE THREAD

**Issue by PaoloC95** [t1m0thyj/WinDynamicDesktop#493] opened 2022-11-27 16:12 UTC
When WDD changes theme  using the official script ( this -> https://raw.githubusercontent.com/t1m0thyj/WDD-scripts/master/stable/ChangeWindowsSystemTheme.ps1 ) sometimes the application bar will be bugged as this screenshot.

![image](https://user-images.githubusercontent.com/43925971/204145017-c2351b64-f5e9-45ff-ae6b-880a8cea54a7.png)

The tray icons and date will not displayed, so i've add at the end of the script the line for restart the explorer ( stop-process -name explorer -force ) but will not work.

Any idea how to fix it?

- WDD Version: 5.1.0
- OS Version: Windows 11 Home 22H2 Build: 22621.819
- Microsoft Store version of WDD?: No

ps. the application bar is setted by the system to hide itself

**Comment by Fnoberz** [comment] 2022-12-07 18:52
@PaoloC95 If you want it to look like MacOS, it shouldn't have a taskbar and it should have a dock that shows it. I recommend you to use " **MydockFinder** " because it's awesome.

![image](https://user-images.githubusercontent.com/94861415/206270171-dd97c066-1832-4dbb-a3d0-13517942f2d2.png)

**Comment by t1m0thyj** [comment] 2023-01-03 01:42
Closing as duplicate of #427

**Closed by t1m0thyj** 2023-01-03 01:42 UTC
