### ISSUE TITLE
Lock screen image before logging on is static!

### ISSUE THREAD

**Issue by yazan1107** [t1m0thyj/WinDynamicDesktop#390] opened 2021-11-21 10:05 UTC
done

- WDD Version: lastest
- OS Version: lastest

Steps to Reproduce:

1. Lock screen image before logging on is static!(doesnot change between restarts)
2. i want it to change to the last image that was before loggin in

Are you using the Microsoft Store version of WDD?: No

**Comment by t1m0thyj** [comment] 2021-12-02 05:46
Duplicate of https://github.com/t1m0thyj/WDD-scripts/issues/1. For more info, see my comment here: https://github.com/t1m0thyj/WinDynamicDesktop/discussions/393#discussioncomment-1734968

**Closed by t1m0thyj** 2021-12-02 05:46 UTC
