### ISSUE TITLE
Wrong Display Name and Numbers

### ISSUE THREAD

**Issue by pc-v2** [t1m0thyj/WinDynamicDesktop#420] opened 2022-03-31 05:18 UTC
- WDD Version: 5.0.0
- OS Version: 22581.200

Steps to Reproduce:

1. Set wallpaper to selected display
2. it inverted 
3. the number 1 shows the second display name and number 2 shows the first 
https://imgur.com/a/g7xQ7Bw
https://imgur.com/a/Agvq6Jo
Are you using the Microsoft Store version of WDD?: No

**Comment by t1m0thyj** [comment] 2022-03-31 12:15
What is your monitor layout shown in the Windows 10 Display settings? Does 1 and 2 in the diagram correspond to "Display 1" and "Display 2"? I have multiple monitors and am not able to reproduce the issue as my displays are listed in the correct order.
![image](https://user-images.githubusercontent.com/22344007/161052296-997dd685-9c7b-4595-9774-f2224ed113e4.png)
![image](https://user-images.githubusercontent.com/22344007/161052379-11ae0f9b-e37a-4268-9640-184812171bdd.png)
![image](https://user-images.githubusercontent.com/22344007/161052449-6a59beaf-53f6-4db4-a607-69d4ddd9c317.png)

**Comment by t1m0thyj** [comment] 2022-03-31 15:46
I have been able to reproduce the issue with a different setup, will look into this.
![image](https://user-images.githubusercontent.com/22344007/161096167-ea3adf76-ed53-437e-8a73-02bc9deefc40.png)
![image](https://user-images.githubusercontent.com/22344007/161096254-0c10e20a-881f-49ea-a113-403c9a923360.png)

**Comment by pc-v2** [comment] 2022-04-01 09:56
> What is your monitor layout shown in the Windows 10 Display settings? Does 1 and 2 in the diagram correspond to "Display 1" and "Display 2"? I have multiple monitors and am not able to reproduce the issue as my displays are listed in the correct order. ![image](https://user-images.githubusercontent.com/22344007/161052296-997dd685-9c7b-4595-9774-f2224ed113e4.png) ![image](https://user-images.githubusercontent.com/22344007/161052379-11ae0f9b-e37a-4268-9640-184812171bdd.png) ![image](https://user-images.githubusercontent.com/22344007/161052449-6a59beaf-53f6-4db4-a607-69d4ddd9c317.png)

like this?

![image](https://user-images.githubusercontent.com/58063311/161241028-6f671c15-bc15-463c-bded-c312d8387c05.png)

**Comment by pc-v2** [comment] 2022-04-04 10:02
the name still inverted in 5.0.1
![image](https://user-images.githubusercontent.com/58063311/161521517-00c77072-d3ef-454b-9304-e716661ceb92.png)
![image](https://user-images.githubusercontent.com/58063311/161521545-c2c46f91-9295-4fae-bb3a-8f46f6d265be.png)

**Comment by t1m0thyj** [comment] 2022-05-27 03:04
This should be fixed in 5.0.2.

**Closed by t1m0thyj** 2022-05-27 03:04 UTC
