### ISSUE TITLE
Change cursor theme when "windows theme" changes(automatically).

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WinDynamicDesktop#484] opened 2022-10-05 07:49 UTC
# What is this feature? 
Change cursor theme when "windows theme" changes(automatically).
# How the feature should work?
windows changes to dark mode(there is alot of application that does this). cursor changes it's theme from light to dark for example
# You have examples or an idea of how it can be implemented?

**Comment by t1m0thyj** [comment] 2022-12-02 15:02
Closing as duplicate of https://github.com/t1m0thyj/WDD-scripts/issues/26

**Closed by t1m0thyj** 2022-12-02 15:02 UTC
