### ISSUE TITLE
Login Screen Wallpaper

### ISSUE THREAD

**Issue by NiklasVoigt** [t1m0thyj/WinDynamicDesktop#269] opened 2020-11-10 20:05 UTC
As the title said. I wish WinDynamicDesktop can change the login screen wallpaper too.

**Comment by t1m0thyj** [comment] 2020-11-13 06:06
Duplicate of #257. There is an experimental script available for WDD that can change lockscreen wallpaper: https://windd.info/scripts/

**Closed by t1m0thyj** 2020-11-13 06:06 UTC
