### ISSUE TITLE
change mouse cursor when dark mode activated

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WinDynamicDesktop#482] opened 2022-10-02 17:17 UTC
change mouse cursor when dark mode activated

change to dark mouse cursor when dark mode activated

**Comment by t1m0thyj** [comment] 2022-12-02 15:01
Closing as duplicate of https://github.com/t1m0thyj/WDD-scripts/issues/26

**Closed by t1m0thyj** 2022-12-02 15:01 UTC
