### ISSUE TITLE
ChangeWindowsAppTheme and ChangeWindowsSystemTheme not working with new 22H2 update.

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WinDynamicDesktop#480] opened 2022-09-30 06:41 UTC
- WDD Version: 5.1.0
- OS Version: 22H2

Steps to Reproduce:

1. enable ChangeWindowsAppTheme and ChangeWindowsSystemTheme.
2. it does not change taskbar color.

Are you using the Microsoft Store version of WDD?: Yes
I am the same i have the same issues as #337 and #463 and https://github.com/t1m0thyj/WDD-scripts/issues/23
taskbar and other apps not respecting wdd scrip:
![taskbar and other apps not respecting wdd script](https://user-images.githubusercontent.com/110556802/193209140-6a076768-8f95-41de-9748-ab34c570b376.png)
i have noticed that if i double toggle the light mode(turning off than on it fixes the issue)

**Comment by direrFlood** [comment] 2022-09-30 06:50
It seems the taskbar is not responding to theme change.

**Comment by shust** [comment] 2022-10-13 17:35
Same problem after update windows

**Comment by swazen** [comment] 2022-12-14 13:01
same too

**Comment by t1m0thyj** [comment] 2023-01-03 01:42
Closing as duplicate of #427

**Closed by t1m0thyj** 2023-01-03 01:42 UTC
